"""
Django settings for transaction_monitor project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-m@ta2y51xbblqylmf#f=7=#pm129mn#fv($0g_n5ba51t!=dpu"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get("DEBUG", "true")).lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_host:
    ALLOWED_HOSTS.append(render_host)
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

CSRF_TRUSTED_ORIGINS = []
if render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{render_host}")

# Persist cache to disk so background commands and the dev server share it.
# Analytics endpoints rely on cache; without this, values computed during ingest may not appear.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "cache",
        "TIMEOUT": 60 * 60,
        "OPTIONS": {"MAX_ENTRIES": 10000, "CULL_FREQUENCY": 10},
    }
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.EnsureAmlDatasetMiddleware",
]

ROOT_URLCONF = "transaction_monitor.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                    "api.context_processors.fing_flags",
            ],
        },
    },
]

WSGI_APPLICATION = "transaction_monitor.wsgi.application"


# Database — set DATABASE_URL for PostgreSQL (e.g. postgres://user:pass@host:5432/dbname)
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_database_url = os.environ.get("DATABASE_URL", "").strip()
if _database_url:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Allow serving generated model insight images from the project-level `static/` folder.
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ML artifact paths
ML_MODEL_PATH = BASE_DIR / "ml_artifacts" / "finguard_best_model.pkl"
ML_PREPROCESSOR_PATH = BASE_DIR / "ml_artifacts" / "finguard_preprocessor.pkl"
ML_THRESHOLD_PATH = BASE_DIR / "ml_artifacts" / "threshold.json"
ML_OPTIMAL_THRESHOLD = 0.603939
ML_MAX_ALERT_ROWS = 2000
ML_CACHE_TIMEOUT_SECONDS = 60 * 60
# Full-scale row caps for case persistence and DB-driven analytics.
try:
    AML_MAX_CASE_PERSIST_ROWS = int(os.environ.get("AML_MAX_CASE_PERSIST_ROWS", "500000"))
except ValueError:
    AML_MAX_CASE_PERSIST_ROWS = 500000
try:
    AML_ANALYTICS_DB_MAX_ROWS = int(os.environ.get("AML_ANALYTICS_DB_MAX_ROWS", "500000"))
except ValueError:
    AML_ANALYTICS_DB_MAX_ROWS = 500000

# Default bundled dataset; auto-sync fills cache + AlertCase rows on first visit if empty.
AML_DATASET_CSV = BASE_DIR / "transactions_dataset.csv"
AML_AUTO_SYNC_DATASET = str(os.environ.get("AML_AUTO_SYNC_DATASET", "true")).lower() in (
    "1",
    "true",
    "yes",
)

# OpenAI (optional): set OPENAI_API_KEY in .env to power the AML chatbot; otherwise rule-based replies are used.
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_CHAT_MODEL = (os.environ.get("OPENAI_CHAT_MODEL", "gpt-4o-mini") or "gpt-4o-mini").strip()
try:
    OPENAI_CHAT_MAX_TOKENS = max(100, min(4096, int(os.environ.get("OPENAI_CHAT_MAX_TOKENS", "900"))))
except ValueError:
    OPENAI_CHAT_MAX_TOKENS = 900
try:
    OPENAI_CHAT_TEMPERATURE = float(os.environ.get("OPENAI_CHAT_TEMPERATURE", "0.25"))
except ValueError:
    OPENAI_CHAT_TEMPERATURE = 0.25
OPENAI_CHAT_TEMPERATURE = max(0.0, min(2.0, OPENAI_CHAT_TEMPERATURE))

# FinGuard case workflow (optional email on assignment)
AML_ASSIGNMENT_EMAIL = str(os.environ.get("AML_ASSIGNMENT_EMAIL", "false")).lower() in (
    "1",
    "true",
    "yes",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

# Auto-assignment for newly generated AlertCases.
# Use ONE of:
# - AML_AUTO_ASSIGN_USER_ID="2" (single assignee)
# - AML_AUTO_ASSIGN_USER_IDS="1,2,3" (pool; round-robin by case index)
# If neither is set, we assign round-robin across users in the "Compliance Officer" group.
AML_AUTO_ASSIGN_USER_ID = os.environ.get("AML_AUTO_ASSIGN_USER_ID", "").strip()
AML_AUTO_ASSIGN_USER_IDS = os.environ.get("AML_AUTO_ASSIGN_USER_IDS", "").strip()
AML_AUTO_ASSIGN_MODE = os.environ.get("AML_AUTO_ASSIGN_MODE", "round_robin").strip().lower()

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/monitoring/"
LOGOUT_REDIRECT_URL = "/login/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Optional: compute SHAP summary plots (requires `shap` and can be slow for huge datasets).
ML_ENABLE_SHAP = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Render / proxy headers
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
